Repository Textualize/textual, pull requests merged in 2023-10, with the labels that each got.

#3290 Recode incoming text on Windows before input event processing
  CHANGELOG.md
  src/textual/drivers/win32.py
Labels: bug, Task

#3424 Command palette lazy command list show
  src/textual/command.py
Labels: enhancement, Task

#3446 Remove an unnecessary a
  docs/guide/CSS.md
Labels: documentation, Task

#3452 `textual-plotext` announcement blogpost
  docs/blog/images/textual-plotext/demo1.png
  docs/blog/images/textual-plotext/demo2.png
  docs/blog/images/textual-plotext/demo3.png
  docs/blog/images/textual-plotext/demo4.png
  docs/blog/images/textual-plotext/scatter.png
  docs/blog/images/textual-plotext/weather.png
  docs/blog/posts/textual-plotext.md
  mkdocs-common.yml
Labels: documentation

#3453 Fix a typo in the textual-plotext blog post
  docs/blog/posts/textual-plotext.md
Labels: documentation, Task

#3458 Remove an unnecessary a
  docs/blog/posts/textual-plotext.md
Labels: documentation

#3459 `OptionList` safe duplicate check
  CHANGELOG.md
  src/textual/widgets/_option_list.py
  tests/option_list/test_option_list_create.py
Labels: bug, Task

#3475 Link to the repo rather than the pypi page
  docs/blog/posts/textual-plotext.md
Labels: documentation, Task

#3485 Add a debug hook for getting sent unknown sequences from the XTerm parser
  src/textual/_xterm_parser.py
Labels: enhancement, Task

#3540 Tweak the docstrings of the ancestors properties
  src/textual/dom.py
Labels: documentation, Task

#3372 Move `Markdown.goto_anchor` change to correct version in `CHANGELOG`
  CHANGELOG.md
Labels: documentation

#3519 Allow F3 with modifier keys
  src/textual/_ansi_sequences.py
Labels: enhancement, Task

#3573 Run CodeQL only on code changes.
  .github/workflows/codeql.yml
Labels: enhancement

#3511 Minor fixes on the actions guide.
  CONTRIBUTING.md
  docs/guide/actions.md
Labels: documentation

#3578 Stop `OptionList.OptionHighlighted` leaking to the `App`
  CHANGELOG.md
  src/textual/command.py
Labels: bug, Task

#3583 Fix notifications CSS.
  CHANGELOG.md
  src/textual/widgets/_toast.py
Labels: bug

#3618 Ensure that the command palette doesn't kill *all* workers when stoping command gathering
  CHANGELOG.md
  src/textual/command.py
  tests/command_palette/test_worker_interference.py
Labels: bug, Task
