Repository Textualize/textual, pull requests merged in 2023-11, with the labels that each got.

#3582 Improve css error reporting
  CHANGELOG.md
  src/textual/app.py
  src/textual/css/_styles_builder.py
  src/textual/css/parse.py
  src/textual/css/query.py
  src/textual/css/styles.py
  src/textual/css/stylesheet.py
  src/textual/css/tokenize.py
  src/textual/css/tokenizer.py
  src/textual/css/types.py
  src/textual/dom.py
  src/textual/widget.py
  tests/css/test_parse.py
  tests/css/test_styles.py
  tests/css/test_tokenize.py
Labels: bug, enhancement

#3644 Chunk writes on Windows
  CHANGELOG.md
  src/textual/app.py
Labels: bug, Task

#3648 More `Makefile` tweaks
  Makefile
Labels: enhancement

#3681 Add missing return type and return detail for `OptionList.get_option_index`
  src/textual/widgets/_option_list.py
Labels: documentation, Task

#3682 Add missing parameter type hint
  src/textual/widgets/_option_list.py
Labels: documentation

#3692 Hide command palette mount and unmount handlers from the docs
  src/textual/command.py
Labels: documentation, Task

#3706 Correct the type hints for ListView.watch_index
  src/textual/widgets/_list_view.py
Labels: Task

#3708 Pause a moment longer when testing the command palette no-matches timeout
  tests/command_palette/test_no_results.py
Labels: enhancement, Task

#3739 Add support for various modified navigation/edit keys under rxvt
  src/textual/_ansi_sequences.py
Labels: enhancement, Task

#3765 Allow setting a toggle button's label
  CHANGELOG.md
  src/textual/widgets/_toggle_button.py
  tests/toggles/test_labels.py
Labels: enhancement

#3737 Add support for ctrl+Fn keys under rxvt
  CHANGELOG.md
  src/textual/_ansi_sequences.py
Labels: enhancement, Task

#3580 Change some log groups
  src/textual/app.py
Labels: needs discussion

#3769 Simplify some sequences that seem unique to rxvt
  CHANGELOG.md
  src/textual/_ansi_sequences.py
  src/textual/_xterm_parser.py
Labels: enhancement, Task
