Repository Textualize/textual, pull requests merged in 2023-02, with the labels that each got.

#1711 Make `textual keys` work on older supported Pythons
  src/textual/cli/previews/keys.py
Labels: bug

#1715 Include the unit tests in the source distribution
  pyproject.toml
Labels: enhancement, Task

#1749 Remove the import/export of TreeNode from the widgets pyi file
  src/textual/widgets/__init__.pyi
Labels: enhancement

#1757 Add setup and update targets to the Makefile
  Makefile
Labels: enhancement

#1761 Add missing link for Checkbox->Switch CHANGELOG entry
  CHANGELOG.md
Labels: documentation

#1760 feat(keys): add space alias to displays
  src/textual/keys.py
Labels: enhancement

#1789 Assorted docstring tidying in dom.py
  src/textual/dom.py
Labels: documentation, enhancement

#1790 Tidy up various docstrings in ListView
  src/textual/widgets/_list_view.py
Labels: documentation, enhancement

#1796 Markdown accept path
  examples/markdown.py
  src/textual/widgets/_markdown.py
Labels: enhancement

#1821 Mark the Markdown viewer as done on the roadmap
  docs/roadmap.md
Labels: documentation

#1827 Switch 5x5's help over to the new Markdown viewer
  examples/five_by_five.css
  examples/five_by_five.md
  examples/five_by_five.py
Labels: enhancement

#1837 Allow numbers in descendant-combined type selectors (fix #1836)
  CHANGELOG.md
  src/textual/css/tokenize.py
  tests/css/test_parse.py
Labels: bug

#1785 Promote disabled to `Widget` level
  CHANGELOG.md
  docs/guide/CSS.md
  examples/five_by_five.py
  src/textual/app.py
  src/textual/dom.py
  src/textual/screen.py
  src/textual/widget.py
  src/textual/widgets/_button.py
  src/textual/widgets/_data_table.py
  src/textual/widgets/_directory_tree.py
  src/textual/widgets/_input.py
  src/textual/widgets/_list_view.py
  src/textual/widgets/_static.py
  src/textual/widgets/_switch.py
  src/textual/widgets/_text_log.py
  src/textual/widgets/_tree.py
  tests/snapshot_tests/__snapshots__/test_snapshots.ambr
  tests/snapshot_tests/snapshot_apps/disable_widgets.py
  tests/snapshot_tests/test_snapshots.py
  tests/test_disabled.py
Labels: enhancement

#1812 Add a couple of extra type hints to reactives
  src/textual/widgets/_button.py
  src/textual/widgets/_placeholder.py
Labels: enhancement

#1857 Swap the 5x5 game header to the alt-compose method
  examples/five_by_five.py
Labels: enhancement

#1862 Textlog docstring
  docs/widgets/text_log.md
  src/textual/widgets/_text_log.py
Labels: documentation, Task

#1867 Correct the wording of the description of `Switch.value`
  docs/widgets/switch.md
Labels: documentation

#1872 Add `Checkbox`, `RadioButton` and `RadioSet`
  CHANGELOG.md
  docs/api/checkbox.md
  docs/api/radiobutton.md
  docs/api/radioset.md
  docs/api/toggle_button.md
  docs/examples/widgets/checkbox.css
  docs/examples/widgets/checkbox.py
  docs/examples/widgets/radio_button.css
  docs/examples/widgets/radio_button.py
  docs/examples/widgets/radio_set.css
  docs/examples/widgets/radio_set.py
  docs/roadmap.md
  docs/widgets/checkbox.md
  docs/widgets/radiobutton.md
  docs/widgets/radioset.md
  mkdocs-nav.yml
  src/textual/app.py
  src/textual/widgets/__init__.py
  src/textual/widgets/__init__.pyi
  src/textual/widgets/_checkbox.py
  src/textual/widgets/_radio_button.py
  src/textual/widgets/_radio_set.py
  src/textual/widgets/_toggle_button.py
  tests/snapshot_tests/__snapshots__/test_snapshots.ambr
  tests/snapshot_tests/test_snapshots.py
  tests/toggles/test_checkbox.py
  tests/toggles/test_radiobutton.py
  tests/toggles/test_radioset.py
Labels: enhancement, Task

#1898 Increase the coverage of API documentation
  docs/api/await_remove.md
  docs/api/binding.md
  docs/api/coordinate.md
  docs/api/dom_node.md
  docs/api/message.md
  docs/api/message_pump.md
  docs/api/scroll_view.md
  docs/api/strip.md
  docs/api/widget.md
  mkdocs-nav.yml
  src/textual/await_remove.py
Labels: documentation, Task
