Repository Textualize/textual, pull requests merged in 2023-03, with the labels that each got.

#1907 A warning from the future
  docs/blog/posts/on-dog-food-the-original-metaverse-and-not-being-bored.md
Labels: documentation

#1906 Highlight that the label acquires an id in the example code
  docs/guide/app.md
Labels: documentation, Task

#1913 Add a Makefile target for installing pre-commit hooks
  Makefile
Labels: enhancement

#1909 Widget documentation sweep
  docs/api/placeholder.md
  docs/api/tree.md
  docs/api/tree_node.md
  docs/api/welcome.md
  mkdocs-nav.yml
  src/textual/widget.py
  src/textual/widgets/_header.py
  src/textual/widgets/_list_item.py
  src/textual/widgets/_placeholder.py
  src/textual/widgets/_pretty.py
  src/textual/widgets/_text_log.py
  src/textual/widgets/_tree.py
  src/textual/widgets/_welcome.py
Labels: documentation, Task

#1917 Tidy up some Button documentation
  docs/api/button.md
  src/textual/widgets/_button.py
Labels: documentation, Task

#1935 Add an example of using a RadioSet.Changed message
  docs/examples/widgets/radio_set_changed.css
  docs/examples/widgets/radio_set_changed.py
  docs/widgets/radioset.md
Labels: documentation

#1951 Windows-friendly toggle buttons
  CHANGELOG.md
  src/textual/widgets/_radio_button.py
  src/textual/widgets/_toggle_button.py
  tests/snapshot_tests/__snapshots__/test_snapshots.ambr
Labels: Task

#1956 Correct the example Python code for the border style
  docs/styles/border.md
Labels: documentation

#1959 Extend the centering Q in the FAQ
  FAQ.md
  questions/align-center-middle.question.md
Labels: documentation

#1964 Add a post-run warning hook to `textual run`
  FAQ.md
  questions/why-looks-bad-on-macos.question.md
  src/textual/cli/cli.py
Labels: documentation, enhancement, Task

#1954 Border colour percentage
  CHANGELOG.md
  docs/styles/border.md
  src/textual/color.py
  src/textual/css/_styles_builder.py
  tests/snapshot_tests/__snapshots__/test_snapshots.ambr
  tests/snapshot_tests/snapshot_apps/border_alpha.py
  tests/snapshot_tests/test_snapshots.py
Labels: enhancement, Task

#1965 Ensure the toggle button keeps any bold state
  src/textual/widgets/_toggle_button.py
  tests/snapshot_tests/__snapshots__/test_snapshots.ambr
Labels: bug, Task

#1978 Extend docs watcher
  mkdocs-common.yml
Labels: documentation

#1997 Swap out the primary Markdown bullet for one that works everywhere
  CHANGELOG.md
  src/textual/widgets/_markdown.py
  tests/snapshot_tests/__snapshots__/test_snapshots.ambr
Labels: Task

#1983 Add `ContentSwitcher`
  CHANGELOG.md
  docs/api/content_switcher.md
  docs/examples/widgets/content_switcher.css
  docs/examples/widgets/content_switcher.py
  docs/widgets/content_switcher.md
  mkdocs-nav.yml
  src/textual/widgets/__init__.py
  src/textual/widgets/__init__.pyi
  src/textual/widgets/_content_switcher.py
  tests/snapshot_tests/__snapshots__/test_snapshots.ambr
  tests/snapshot_tests/test_snapshots.py
  tests/test_content_switcher.py
Labels: enhancement, Task

#2034 Updates to `Pilot.click`
  CHANGELOG.md
  src/textual/pilot.py
Labels: bug, enhancement, Task

#2037 Pilot can now press _
  CHANGELOG.md
  src/textual/app.py
  tests/snapshot_tests/test_snapshots.py
  tests/test_pilot.py
Labels: enhancement, Task

#2038 Change how to determine whether a message needs an updated namespace
  CHANGELOG.md
  src/textual/message_pump.py
  tests/test_message_handling.py
Labels: bug, Task

#2039 Simplify the disabled widgets snapshot test
  tests/snapshot_tests/__snapshots__/test_snapshots.ambr
  tests/snapshot_tests/snapshot_apps/disable_widgets.py
Labels: Task

#2047 Fix a typo in example code in the 0.14.0 release blog post
  docs/blog/posts/release0-14-0.md
Labels: documentation, Task

#2046 Make the Python code for dock.md more... Pythonic
  docs/styles/dock.md
Labels: documentation, Task

#2045 Ensure that `Tab` is available from `textual.widgets`
  CHANGELOG.md
  src/textual/widgets/_tab.py
Labels: bug, Task

#2041 Simplify namespace for inherited messages from ToggleButton
  src/textual/widgets/_checkbox.py
  src/textual/widgets/_radio_button.py
Labels: enhancement

#2057 Add some initial rules to a "mega stylesheet"
  tests/css/test_mega_stylesheet.css
  tests/css/test_mega_stylesheet.py
Labels: Task

#2154 Add `OptionList` widget
  CHANGELOG.md
  docs/api/option_list.md
  docs/examples/widgets/option_list.css
  docs/examples/widgets/option_list_options.py
  docs/examples/widgets/option_list_strings.py
  docs/examples/widgets/option_list_tables.py
  docs/widget_gallery.md
  docs/widgets/option_list.md
  mkdocs-nav.yml
  src/textual/message_pump.py
  src/textual/widgets/__init__.py
  src/textual/widgets/__init__.pyi
  src/textual/widgets/_option_list.py
  src/textual/widgets/option_list.py
  tests/option_list/test_option_list_create.py
  tests/option_list/test_option_list_disabled.py
  tests/option_list/test_option_list_mouse_hover.py
  tests/option_list/test_option_list_movement.py
  tests/option_list/test_option_list_option_subclass.py
  tests/option_list/test_option_messages.py
  tests/option_list/test_option_removal.py
  tests/snapshot_tests/__snapshots__/test_snapshots.ambr
  tests/snapshot_tests/test_snapshots.py
Labels: enhancement, Task
