Repository Textualize/textual, pull requests merged in 2023-01, with the labels that each got.

#1487 Add public access (both get and set) to the `label` of a `TreeNode`
  CHANGELOG.md
  src/textual/widgets/_tree.py
  tests/tree/test_tree_node_label.py
Labels: enhancement

#1488 Add a public read-only parent property to TreeNode
  CHANGELOG.md
  src/textual/widgets/_tree.py
  tests/tree/test_tree_node_parent.py
Labels: enhancement

#1495 Add read-only access to the children of a `TreeNode`
  CHANGELOG.md
  src/textual/_immutable_sequence_view.py
  src/textual/widgets/_tree.py
  tests/test_immutable_sequence_view.py
  tests/tree/test_tree_node_children.py
Labels: enhancement

#1545 Add a textual diagnose CLI command
  CHANGELOG.md
  src/textual/cli/cli.py
  src/textual/cli/tools/__init__.py
  src/textual/cli/tools/diagnose.py
Labels: enhancement, Task

#1549 Textual diagnose command code tweaks
  src/textual/cli/tools/diagnose.py
Labels: enhancement

#1561 Tweak `query_one` and related methods docstrings
  src/textual/css/query.py
  src/textual/dom.py
Labels: documentation, enhancement

#1570 Add docstrings to app title an sub-titles
  src/textual/app.py
Labels: documentation, enhancement, Task

#1550 Allow by-code scrolling even when by-input scrolling would be denied
  CHANGELOG.md
  src/textual/widget.py
Labels: enhancement, Task

#1591 Reraise compose TypeError from the error rather than None
  CHANGELOG.md
  src/textual/app.py
  src/textual/widget.py
Labels: enhancement

#1598 Seek to improve the explanation of what a percentage does
  docs/guide/styles.md
Labels: documentation

#1600 Allow populating a child class of `ListView` purely from its `compose`
  CHANGELOG.md
  src/textual/widgets/_list_view.py
  tests/listview/test_inherit_listview.py
Labels: bug

#1623 Import type annotations from the future for `textual diagnose`
  CHANGELOG.md
  src/textual/cli/tools/diagnose.py
Labels: bug

#1639 Remove some parameter types that got missed on `Widget.move_child`
  src/textual/widget.py
Labels: documentation

#1633 Catch an attempt to use the `textual` command in a non-dev context
  src/textual/cli/cli.py
Labels: enhancement

#1641 Explain the significance of the before/after types
  src/textual/widget.py
Labels: documentation

#1652 Remove mention of `ChildrenUpdated` from the `ListView` docs
  docs/widgets/list_view.md
Labels: documentation

#1656 Explain the significance of the before/after types (redux)
  src/textual/app.py
Labels: documentation

#1660 Fix double-paste into `Input`
  CHANGELOG.md
  src/textual/widgets/_input.py
Labels: bug

#1637 Support easier widget "support classes" importing
  CHANGELOG.md
  examples/json_tree.py
  src/textual/widgets/__init__.py
  src/textual/widgets/_tree_node.py
  src/textual/widgets/data_table.py
  src/textual/widgets/tree.py
  tests/tree/test_tree_node_children.py
  tests/tree/test_tree_node_label.py
  tests/tree/test_tree_node_parent.py
Labels: enhancement

#1653 Rhymes with "Bed rock"
  src/textual/_context.py
  src/textual/app.py
  src/textual/await_remove.py
  src/textual/message_pump.py
  src/textual/widget.py
  tests/test_widget.py
Labels: enhancement, Task

#1665 Workaround for a Windows paste issue
  CHANGELOG.md
  src/textual/_xterm_parser.py
Labels: enhancement

#1676 [WiP] More input bindings
  CHANGELOG.md
  src/textual/widgets/_input.py
  tests/input/test_input_key_modification_actions.py
  tests/input/test_input_key_movement_actions.py
  tests/input/test_input_value_visibility.py
Labels: enhancement

#1644 Add support for a method of expanding/collapsing all tree nodes from a given node down
  CHANGELOG.md
  src/textual/widgets/_tree.py
  tests/tree/test_tree_expand_etc.py
Labels: enhancement

#1694 When in password mode have word-oriented actions act on whole input
  src/textual/widgets/_input.py
  tests/input/test_input_key_modification_actions.py
  tests/input/test_input_key_movement_actions.py
Labels: enhancement, Task

#1700 Enhance `Tree` so that there is a expand/collapse action that is separate from select
  CHANGELOG.md
  src/textual/widgets/_tree.py
  tests/tree/test_tree_messages.py
Labels: enhancement, Task

#1703 Lowkey tree selection
  CHANGELOG.md
  src/textual/widgets/_tree.py
  tests/snapshot_tests/__snapshots__/test_snapshots.ambr
Labels: enhancement, Task
