Repository Textualize/textual, pull requests merged in 2023-08, with the labels that each got.

#3024 Fix the page up/down bindings for OptionList
  src/textual/widgets/_option_list.py
  tests/option_list/test_option_list_movement.py
Labels: bug, Task

#3019 Tidy up the notes in the `stop_animation` docstrings
  src/textual/_animator.py
  src/textual/app.py
  src/textual/widget.py
Labels: documentation, Task

#3038 Add a test for Select.value being set from the constructor
  tests/select/test_initial_value.py
Labels: Task

#3128 Link the `Header` docs to `App.title` and `App.sub_title`
  docs/examples/widgets/header_app_title.py
  docs/widgets/header.md
Labels: documentation, enhancement, Task

#3119 Ensure the screenshot path is escaped when telling on it
  src/textual/demo.py
Labels: bug, Task

#3129 Move the Textual FAQ into the main docs
  .faq/FAQ.md
  Makefile
  docs/FAQ.md
  faq.yml
  mkdocs-nav.yml
Labels: documentation, Task

#3152 Allow enabling/disabling tab via tab pane.
  CHANGELOG.md
  src/textual/widgets/_tabbed_content.py
  src/textual/widgets/_tabs.py
  tests/test_tabbed_content.py
Labels: enhancement

#3142 Reinstate the FAQtory-friendly links in the FAQ
  .faq/FAQ.md
  docs/FAQ.md
Labels: documentation, Task

#3070 Consider visible children inside invisible containers when computing focus chain
  CHANGELOG.md
  src/textual/dom.py
  src/textual/screen.py
  src/textual/widget.py
  tests/test_focus.py
  tests/test_visibility_change.py
  tests/test_visible.py
Labels: bug, enhancement

#3169 Let layers be strings.
  CHANGELOG.md
  src/textual/css/_styles_builder.py
Labels: question

#3212 Reword the description of the buttons for a RadioSet
  src/textual/widgets/_radio_set.py
Labels: documentation, Task
