Repository Textualize/textual, pull requests merged in 2023-09, with the labels that each got.

#3232 Add see-also entries to the various blur/focus messages
  docs/events/blur.md
  docs/events/descendant_blur.md
  docs/events/descendant_focus.md
  docs/events/focus.md
Labels: documentation

#3236 Add utility code for generating Markdown-oriented slugs
  src/textual/_slug.py
  tests/test_slug.py
Labels: enhancement

#3274 Fix an OptionList crash when removing an option during mouse hover
  CHANGELOG.md
  src/textual/widgets/_option_list.py
  tests/option_list/test_option_removal.py
Labels: bug, Task

#3203 feat(directory tree): add directory selected message
  CHANGELOG.md
  src/textual/widgets/_directory_tree.py
  tests/tree/test_directory_tree.py
Labels: enhancement

#3244 Fix Markdown anchor load crash, and support going to an heading on document load
  CHANGELOG.md
  examples/markdown.py
  src/textual/widgets/_markdown.py
  tests/test_markdownviewer.py
Labels: bug, enhancement, Task

#3287 Update the blog author metadata
  docs/blog/.authors.yml
Labels: documentation, Task

#3296 Remove an unused import from command.py
  src/textual/command.py
Labels: Task

#3297 Remove unused grab of the match component style
  src/textual/command.py
Labels: Task

#3300 Remove assertion that the calling screen is not None
  src/textual/command.py
Labels: Task

#3321 Fix command palette `TimeoutError` error
  CHANGELOG.md
  src/textual/command.py
Labels: bug, Task

#3322 Stop command palette `Input` message leakage
  CHANGELOG.md
  src/textual/command.py
Labels: bug, Task

#3331 Fix command palette docs example
  docs/examples/guide/command_palette/command01.py
Labels: bug, documentation, Task

#3337 Fix heading in changelog for 0.37.0
  CHANGELOG.md
Labels: documentation

#3348 Mark the command palette as existing
  docs/roadmap.md
Labels: documentation, Task

#3383 Don't document `TextArea` `language` and `theme` twice
  src/textual/widgets/_text_area.py
Labels: documentation, Task

#3409 fix Tree(disabled=True) breaking app
  CHANGELOG.md
  src/textual/widgets/_tree.py
  tests/tree/test_tree_availability.py
Labels: bug

#3371 Tick off `TextArea`-related items on the roadmap
  docs/roadmap.md
Labels: documentation

#3416 Fix component classes section for sparkline widget.
  docs/widgets/sparkline.md
Labels: documentation

#3399 Add countdown to showing command palette `no matches` message
  CHANGELOG.md
  src/textual/command.py
  tests/command_palette/test_no_results.py
Labels: enhancement, Task
