Repository Textualize/textual, pull requests merged in 2023-04, with the labels that each got.

#2197 Property docstring tidying
  src/textual/app.py
Labels: documentation

#2174 Add FAQ about some keys not making it to a Textual app
  FAQ.md
  Makefile
  questions/why-do-some-keys-not-make-it-to-my-app.question.md
Labels: documentation, Task

#2205 Rework `RadioSet` so it no longer leans on the DOM for state
  CHANGELOG.md
  src/textual/widgets/_radio_set.py
  tests/toggles/test_radioset.py
Labels: bug, Task

#2217 Wee tidy of some docstrings in _markdown.py
  src/textual/widgets/_markdown.py
Labels: documentation

#2287 Export button variant
  CHANGELOG.md
  docs/widgets/button.md
  src/textual/widgets/button.py
Labels: documentation, enhancement

#2286 Update the centring FAQ to reference `Center`
  FAQ.md
  questions/align-center-middle.question.md
Labels: documentation, Task

#2302 Ensure the active message pump is set when app is the sender
  CHANGELOG.md
  src/textual/app.py
Labels: bug, Task

#2300 Don't expose snippets publically.
  mkdocs-common.yml
  mkdocs-nav.yml
Labels: documentation, enhancement

#2325 Make textual.widgets.* event handlers private
  src/textual/widgets/_content_switcher.py
  src/textual/widgets/_data_table.py
  src/textual/widgets/_directory_tree.py
  src/textual/widgets/_header.py
  src/textual/widgets/_input.py
  src/textual/widgets/_list_item.py
  src/textual/widgets/_list_view.py
  src/textual/widgets/_loading_indicator.py
  src/textual/widgets/_markdown.py
  src/textual/widgets/_option_list.py
  src/textual/widgets/_placeholder.py
  src/textual/widgets/_radio_set.py
  src/textual/widgets/_switch.py
  src/textual/widgets/_tabs.py
  src/textual/widgets/_toggle_button.py
Labels: enhancement, Task

#2321 Add support for "returning" a result value from screens.
  src/textual/app.py
  src/textual/screen.py
Labels: enhancement, Task

#2339 Ensure an app's CSS refresh updates all screens in the stack
  CHANGELOG.md
  src/textual/app.py
Labels: bug, Task

#2337 Move default scroll navigation keys out of `Widget` and into `ScrollableContainer`
  CHANGELOG.md
  src/textual/containers.py
  src/textual/demo.py
  src/textual/scroll_view.py
  src/textual/widget.py
  tests/test_binding_inheritance.py
Labels: bug, enhancement, Task

#2340 Assorted doc tweaks
  src/textual/widgets/_checkbox.py
  src/textual/widgets/_content_switcher.py
  src/textual/widgets/_radio_button.py
  src/textual/widgets/_radio_set.py
Labels: documentation

#2344 Small improvement to the `Button.Pressed` event documentation
  src/textual/widgets/_button.py
Labels: documentation

#2345 Some more Button docs tidying
  src/textual/widgets/_button.py
Labels: documentation

#2353 Fix `TabbedContent.active` not changing actual content
  CHANGELOG.md
  src/textual/widgets/_tabbed_content.py
  tests/test_tabbed_content.py
Labels: bug, Task

#2386 Make `textual.containers` `1fr` in meaningful dimensions by default
  CHANGELOG.md
  src/textual/containers.py
  src/textual/widgets/_progress_bar.py
Labels: bug, enhancement, Task

#2402 Fix light mode plain text in non-syntax code blocks in Markdown
  CHANGELOG.md
  src/textual/widgets/_markdown.py
Labels: bug, Task

#2415 Add `TreeNode.tree`
  CHANGELOG.md
  src/textual/widgets/_tree.py
  tests/tree/test_tree_messages.py
Labels: enhancement, Task
