Repository Textualize/textual, pull requests merged in 2023-12, with the labels that each got.

#3786 Force the call to scroll to the region of a node's label
  CHANGELOG.md
  src/textual/widgets/_tree.py
Labels: bug, Task

#3828 Fix a typo in docs for OptionList
  docs/widgets/option_list.md
Labels: documentation

#3871 handle cities with spaces in the urllib.request version of weather05.py
  docs/examples/guide/workers/weather05.py
Labels: bug

#3815 Namespace IDs for `ContentTab` in `TabbedContent`
  CHANGELOG.md
  docs/examples/widgets/tabbed_content_label_color.py
  docs/widgets/tabbed_content.md
  src/textual/widgets/_tabbed_content.py
  tests/snapshot_tests/snapshot_apps/modified_tabs.py
  tests/test_on.py
  tests/test_tabbed_content.py
Labels: enhancement, Task
