Repository Textualize/textual, pull requests merged in 2023-05, with the labels that each got.

#2442 Add support for private watch methods
  CHANGELOG.md
  src/textual/reactive.py
  tests/test_reactive.py
Labels: enhancement, Task

#2444 Make `!important` apply to rules that have "sub-rules"
  CHANGELOG.md
  src/textual/css/_styles_builder.py
  tests/test_style_importance.py
Labels: bug, Task

#2452 Fix outline-top and outline-bottom not handling colour alpha
  CHANGELOG.md
  src/textual/_styles_cache.py
Labels: bug, Task

#2454 Attempt to narrow CI/test trigger to just code changes
  .github/workflows/pythonpackage.yml
Labels: enhancement, Task

#2455 Remove the bytewise diffing of failed snapshots
  tests/snapshot_tests/conftest.py
Labels: enhancement, Task

#2463 Allow changing the "root" of a `DirectoryTree`
  CHANGELOG.md
  src/textual/widgets/_directory_tree.py
Labels: enhancement, Task

#2473 Fix a crash when `DirectoryTree` starts out anywhere other than `.`
  CHANGELOG.md
  src/textual/widgets/_directory_tree.py
Labels: bug, Task

#2477 Datatable scrolling faq
  FAQ.md
  questions/datatable-doesnt-scroll.question.md
Labels: documentation, enhancement

#2482 Fix the drawing of `Tree` lines in respect to things being `selected`
  CHANGELOG.md
  src/textual/reactive.py
  src/textual/widgets/_tree.py
Labels: bug, Task

#2485 Add some extra tests for the toggle-related controls
  tests/toggles/test_checkbox.py
  tests/toggles/test_radiobutton.py
  tests/toggles/test_radioset.py
Labels: enhancement, Task

#2479 Add `DataTable.move_cursor`
  CHANGELOG.md
  src/textual/widgets/_data_table.py
  tests/test_data_table.py
Labels: enhancement, Task

#2497 Fix TabbedContent __init__ signature.
  CHANGELOG.md
  src/textual/widgets/_tabbed_content.py
Labels: bug

#2508 Add `add_options` to `OptionList`
  CHANGELOG.md
  docs/examples/widgets/option_list_tables.py
  src/textual/widgets/_option_list.py
  tests/option_list/test_option_list_create.py
  tests/snapshot_tests/__snapshots__/test_snapshots.ambr
  tests/snapshot_tests/snapshot_apps/option_list.py
  tests/snapshot_tests/test_snapshots.py
Labels: enhancement, Task

#2510 Add the ability to remove nodes from a `Tree`
  CHANGELOG.md
  src/textual/widgets/_tree.py
  tests/tree/test_tree_clearing.py
Labels: enhancement, Task

#2483 Add 'control' alias to Tabs messages.
  CHANGELOG.md
  src/textual/widgets/_tabs.py
Labels: enhancement, Task

#2490 Add control to widget messages.
  CHANGELOG.md
  docs/widgets/option_list.md
  src/textual/widgets/_directory_tree.py
  src/textual/widgets/_list_view.py
  src/textual/widgets/_markdown.py
  src/textual/widgets/_option_list.py
  src/textual/widgets/_radio_set.py
  src/textual/widgets/_tabbed_content.py
  src/textual/widgets/_tree.py
Labels: enhancement, Task

#2522 Make the widget moving tests more granular and add more tests
  tests/test_widget_child_moving.py
Labels: bug, enhancement, Task

#2519 Fix for `resolve_fraction_unit` zero division error (#2502)
  CHANGELOG.md
  src/textual/_resolve.py
  tests/test_resolve.py
Labels: bug, Task

#2552 Correct spelling in a docstring
  src/textual/dom.py
Labels: documentation

#2530 Moving child before/after self is a no-op.
  CHANGELOG.md
  src/textual/widget.py
  tests/test_widget_child_moving.py
Labels: Task

#2568 Fix empty paste
  CHANGELOG.md
  src/textual/widgets/_input.py
  tests/test_paste.py
Labels: bug

#2567 Fix clearing an OptionList
  src/textual/widgets/_option_list.py
  tests/snapshot_tests/__snapshots__/test_snapshots.ambr
  tests/snapshot_tests/snapshot_apps/select_rebuild.py
  tests/snapshot_tests/test_snapshots.py
Labels: bug, Task

#2545 Load `DirectoryTree` contents in a worker
  CHANGELOG.md
  src/textual/widgets/_directory_tree.py
Labels: enhancement, Task

#2540 Implements screen modes
  src/textual/app.py
  tests/test_screen_modes.py
Labels: enhancement

#2610 Let child classes of DirectoryTree override Path creation
  src/textual/widgets/_directory_tree.py
Labels: enhancement

#2626 Fix a copy/pasteo in an option list docstring
  src/textual/widgets/_option_list.py
Labels: documentation

#2636 Fix Select reactives table layout
  docs/widgets/select.md
Labels: documentation, Task

#2640 Include `widgets.option_list.Option` in the docs
  docs/widgets/option_list.md
Labels: documentation

#2647 Fix docstring for `DOMNode.set_classes`
  src/textual/dom.py
Labels: documentation

#2654 Fix progress bar docs issue.
  src/textual/widgets/_progress_bar.py
Labels: documentation, Task

#2660 `DirectoryTree` "belt and braces" tweaks
  src/textual/widgets/_directory_tree.py
Labels: bug

#2677 Revisit allowing building the docs without access to "Material for MkDocs Insiders"
  mkdocs-common.yml
  mkdocs-offline.yml
  mkdocs-online.yml
Labels: documentation, Task

#2679 Fix the dock type warning
  src/textual/css/_style_properties.py
Labels: bug

#2701 Improve `OptionList` test coverage
  tests/option_list/test_option_list_mouse_hover.py
  tests/option_list/test_option_messages.py
Labels: enhancement
