Repository Textualize/textual, pull requests merged in 2024-02, with the labels that each got.

#4103 Fix broken OptionList Option id mapping
  CHANGELOG.md
  src/textual/widgets/_option_list.py
  tests/option_list/test_option_list_id_stability.py
Labels: bug

#4105 Only perform the SIGTOU check in the Linux driver when hooked up to a tty
  CHANGELOG.md
  src/textual/drivers/linux_driver.py
Labels: bug, Task

#4040 Allow lists of nested selectors and allow styles after nested CSS blocks
  CHANGELOG.md
  src/textual/css/tokenize.py
  tests/css/test_nested_css.py
Labels: bug

#4159 Fix active tab not coming into view plus `TabbedContent.TabActivated` not always been posted
  CHANGELOG.md
  src/textual/widgets/_tabbed_content.py
  src/textual/widgets/_tabs.py
  tests/test_tabbed_content.py
Labels: bug, Task

#4178 Remove double-up scrolling of active tab
  src/textual/widgets/_tabs.py
Labels: bug, Task

#4181 Add support for specifying the screenshot location and filename
  CHANGELOG.md
  src/textual/app.py
  src/textual/constants.py
Labels: enhancement, Task

#4189 Fix syntax warning in `LoadingIndicator` code
  CHANGELOG.md
  src/textual/widgets/_loading_indicator.py
Labels: bug, Task

#4196 Allow a `deque` to work as data for a `Sparkline`
  CHANGELOG.md
  src/textual/renderables/sparkline.py
  tests/renderables/test_sparkline.py
Labels: bug, Task

#4191 Tooltip clearing on layout changes
  CHANGELOG.md
  src/textual/pilot.py
  src/textual/screen.py
  tests/test_tooltips.py
Labels: enhancement, Task

#4210 Fix DirectoryTree.path no longer reacting to new values
  CHANGELOG.md
  src/textual/widgets/_directory_tree.py
  tests/directory_tree/test_change_path.py
Labels: bug, Task

#4222 Correct the sender of a reactive-posted message
  src/textual/reactive.py
  tests/test_reactive.py
Labels: bug, Task

#4235 Expose `Message._set_sender` as a utility method
  src/textual/app.py
  src/textual/driver.py
  src/textual/message.py
Labels: enhancement, Task

#4240 Fix docs order.
  mkdocs-nav.yml
Labels: documentation
