Repository Textualize/textual, pull requests merged in 2024-01, with the labels that each got.

#3965 Fix `DataTable.move_cursor(..., animate)`
  CHANGELOG.md
  src/textual/widgets/_data_table.py
  tests/test_data_table.py
Labels: bug

#3800 Improve the method via which unsupported sequences are ignored
  src/textual/_ansi_sequences.py
  src/textual/_xterm_parser.py
Labels: enhancement, Task

#3981 Apply css changes screen stack
  CHANGELOG.md
  src/textual/app.py
  tests/css/css_reloading.tcss
  tests/css/test_css_reloading.py
Labels: bug

#4025 Fix a typo in the docs for scoped CSS
  docs/guide/widgets.md
Labels: documentation, Task

#4059 Increase the default notification timeout period
  CHANGELOG.md
  src/textual/notifications.py
  tests/notifications/test_notification.py
Labels: enhancement, Task

#4064 Application suspension
  CHANGELOG.md
  docs/api/signal.md
  docs/examples/app/suspend.py
  docs/examples/app/suspend_process.py
  docs/guide/actions.md
  docs/guide/app.md
  src/textual/app.py
  src/textual/driver.py
  src/textual/drivers/linux_driver.py
  src/textual/drivers/win32.py
  src/textual/drivers/windows_driver.py
  src/textual/signal.py
  tests/test_binding_inheritance.py
  tests/test_suspend.py
Labels: enhancement, Task

#4082 Fix the double-detection of `escape` on Windows
  CHANGELOG.md
  src/textual/drivers/win32.py
Labels: bug, Task

#4083 Small simplification to the composition of `ProgressBar`
  src/textual/widgets/_progress_bar.py
Labels: enhancement, Task
