Repository Textualize/textual, pull requests merged in 2024-03, with the labels that each got.

#4264 Clean render return type
  docs/examples/how-to/render_compose.py
  src/textual/app.py
  src/textual/widget.py
  src/textual/widgets/_button.py
  src/textual/widgets/_digits.py
  src/textual/widgets/_footer.py
  src/textual/widgets/_input.py
  src/textual/widgets/_loading_indicator.py
  src/textual/widgets/_placeholder.py
  src/textual/widgets/_static.py
  src/textual/widgets/_switch.py
  src/textual/widgets/_toast.py
Labels: enhancement, Task

#4280 Stop `OptionList.OptionHighlighted` leaking out of `Select`
  CHANGELOG.md
  src/textual/widgets/_select.py
Labels: bug, Task

#4284 Change `TextArea` to delete empty line on ctrl+k
  CHANGELOG.md
  src/textual/widgets/_text_area.py
Labels: enhancement, Task

#4285 Ensure TabbedContent only handles tab messages intended for it
  CHANGELOG.md
  src/textual/widgets/_tabbed_content.py
  tests/test_tabbed_content.py
Labels: bug, Task

#4291 Ensure scrollbars get Show/Hide messages
  CHANGELOG.md
  src/textual/widget.py
Labels: bug, Task

#4295 Fix `TextArea` holding on to focus when hidden while doing a mouse selection
  CHANGELOG.md
  src/textual/widgets/_text_area.py
Labels: bug, Task

#4297 Let mouse scroll events pass through disabled widgets
  CHANGELOG.md
  src/textual/widget.py
Labels: bug, Task

#4309 Fix `TextArea` display corruption/crash after undo of reverse-selected replacement
  CHANGELOG.md
  src/textual/widgets/_text_area.py
  tests/text_area/test_issue_4301.py
Labels: bug, Task

#4337 Fix a typo in the docstring for the Unmount event
  src/textual/events.py
Labels: documentation

#4338 Add the Unmount event to the docs
  docs/events/unmount.md
  mkdocs-nav.yml
Labels: documentation

#4313 Fix a crash in `run_action` when an action is an empty tuple
  src/textual/app.py
  tests/test_issue_4248.py
Labels: bug, Task

#4340 Add see-alsos relating to (un)mounting
  docs/events/load.md
  docs/events/mount.md
  docs/events/unmount.md
Labels: documentation

#4349 Typo
  docs/guide/animation.md
Labels: documentation

#4362 Clarify that `SelectionList` can use Rich Text
  docs/widgets/selection_list.md
Labels: documentation
